import pygame

enemy_image = pygame.image.load('image/enemy/right.png')
bottom_image = pygame.image.load('image/tile map/bottom.png')
bush_image = pygame.image.load('image/tile map/bush_tile 1.png')
bush_tower_image = pygame.image.load('image/tile map/bush_tile_tower.png')
grass_image = pygame.image.load('image/tile map/grass_tile_1.png')
left_image = pygame.image.load('image/tile map/left.png')
rigth_image = pygame.image.load('image/tile map/right.png')
top_image = pygame.image.load('image/tile map/top.png')
toweron_image = pygame.image.load('image/tower 1/1_on.png')
towerof_image = pygame.image.load('image/tower 1/1_of.png')
bullet_image = pygame.image.load('image/tower 1/bullet 1.png')
panel_image = pygame.image.load('image/panel.jpg')
upgrade_image = pygame.image.load('image/upgrade.png')